### ISSUE TITLE
Swift build command fails, because DispatchQueueAttr.swift wasn't deleted

### ISSUE THREAD

**Issue by ElvishJerricco** [anpol/DispatchKit#9]
## Problem

15de079 removed DispatchQueueAttr.swift from the Xcode project, but the file still exists in the Sources directory. Thus, the swift build command fails.
## Solution

Remove the DispatchQueueAttr.swift file from the git repository before the next release.

EDIT: Wrote the wrong commit down in the first paragraph

**Comment by anpol** [comment]
Removed in bff2c97
